name: 'GraphQL Compose: Fragments'
description: 'Redundant module stub to be removed on RC.'
type: module
core_version_requirement: ^9.5 || ^10
php: 8.1
package: GraphQL Compose
hidden: true

# Information added by Drupal.org packaging script on 2023-09-05
version: '2.0.0-beta11'
project: 'graphql_compose'
datestamp: 1693898582
