<?php

/**
 * @file
 * EBT Core remove helpers.
 */

use Drupal\block_content\Entity\BlockContent;

/**
 * Fetch batch operations.
 */
function _ebt_core_remove_helper_remove_blocks($bids, $type, &$context) {
  $message = 'Deleting ALL EBT blocks ...';
  $results = [];
  foreach ($bids as $bid) {
    $block = BlockContent::load($bid);
    $results[] = $block->delete();
  }

  $context['message'] = $message;
  $context['results'] = $results;
}

/**
 * Display results message.
 */
function _ebt_core_remove_helper_remove_blocks_finished($success, $results, $operations) {
  // The 'success' parameter means no fatal PHP errors were detected. All
  // other error management should be handled using 'results'.
  if ($success) {
    $message = \Drupal::translation()->formatPlural(
      count($results),
      'One EBT block processed.', '@count blocks processed.'
    );
  }
  else {
    $message = t('Finished with an error.');
  }
  \Drupal::messenger()->addStatus($message);
}
