aws.settings:
  type: config_object
  label: Settings
  mapping:
    services:
      type: sequence
      sequence:
        type: aws_profile.[%key]

aws_profile.*:
  type: mapping
  mapping:
    profile:
      type: string
      label: 'Profile'
    version:
      type: string
      label: 'Version'
