# Schema for the configuration files of the jsonlog module.

jsonlog.settings:
  type: config_object
  label: 'Jsonlog settings'
  mapping:
    jsonlog_severity_threshold:
      type: integer
      label: 'Do not log events that are less severe than'
    jsonlog_channels:
      type: string
      label: 'Log channels'
    jsonlog_truncate:
      type: integer
      label: 'Truncate events to'
    jsonlog_siteid:
      type: string
      label: 'Site ID'
    jsonlog_canonical:
      type: string
      label: 'Canonical site name'
    jsonlog_file_time:
      type: string
      label: 'Timestamped log file name'
    jsonlog_dir:
      type: string
      label: 'Log directory'
    jsonlog_stdout:
      type: boolean
      nullable: true
      label: 'Log to STDOUT'
    jsonlog_newline_prepend:
      type: boolean
      # Nullable because is addition to original schema.
      # Null default, see Drupal\jsonlog\Logger\JsonLog::JSONLOG_NEWLINE_PREPEND
      nullable: true
      label: 'Prepend newline when filing log entry'
    jsonlog_tags:
      type: string
      label: 'Tags'
