# Field widget third-party settings.
# See paragraphs_sets_field_widget_settings_summary_alter().
field.widget.third_party.paragraphs_sets:
  type: mapping
  label: 'Paragraphs sets settings per paragraphs reference field'
  mapping:
    paragraphs_sets:
      type: mapping
      mapping:
        use_paragraphs_sets:
          type: boolean
          label: 'Enable Paragraphs Sets'
        sets_allowed:
          type: sequence
          label: 'Limit sets to'
          nullable: true
        default_set:
          type: string
          label: 'Default set'
          nullable: true

# Paragraphs Set configuration entity.
# See \Drupal\paragraphs_sets\Entity\ParagraphsSet and
# \Drupal\paragraphs_sets\Form\ParagraphsSetForm.
paragraphs_sets.set.*:
  type: config_entity
  label: 'Paragraphs set'
  mapping:
    id:
      type: string
    description:
      type: text
      label: 'Description'
      nullable: true
    label:
      type: label
      label: 'Label'
    icon_uuid:
      type: string
      label: 'Icon uuid'
      nullable: true
    paragraphs:
      type: sequence
      label: 'Paragraphs configuration'
      sequence:
        type: mapping
        mapping:
          bundle:
            type: string
            label: 'Paragraph machine name'
          data:
            type: sequence
            label: 'Field default values (map field names to default values)'
            nullable: true
            sequence:
              type: ignore
